language: php

php:
  - 7.2
  
branches:
  only:
  - master
  
script:
  - composer config secure-http false
  - composer update --ignore-platform-reqs
  - composer install --no-dev
 
after_success:
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git checkout -b source
  - git push --quiet --force https://$rocket@github.com/fydy/wp-rocket.git source
